# Generated by Django 3.1.7 on 2021-03-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_counter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
