# Generated by Django 3.1.7 on 2021-04-01 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('word_counter_app', '0002_number_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='email',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
