# Generated by Django 3.1.7 on 2021-04-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_counter_app', '0004_auto_20210401_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='email',
        ),
    ]
