# Generated by Django 3.1.7 on 2021-04-06 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('word_counter_app', '0006_auto_20210405_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='t1',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='t2',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
